CREATE DATABASE point;
USE point;

CREATE TABLE user(
id INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(50),
pass VARCHAR(50) NOT NULL,
full_name LONGTEXT
);
CREATE TABLE product(
code INT(13) NOT NULL PRIMARY KEY,
name VARCHAR(50),
quantity INT(10),
price FLOAT(7,2)
);
CREATE TABLE daily_sales(
date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
quantity FLOAT(10,2)
);