/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package point_of_sale;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import views.*;
import SQL.connection;
import java.util.List;
import objects.*;
/**
 *
 * @author juanchis
 */
public class principal extends javax.swing.JFrame implements Runnable{
    Thread hilo;
    boolean hil=true;
    /**
     * Creates new form principal
     */
    public principal() {
        hilo = new Thread(this);
        hilo.start();
     }
    public principal(boolean t){
        initComponents();
         to_sell s = new to_sell();
        s.setSize(900,500);
        s.setLocation(5, 5);
        panel.removeAll();
        panel.repaint();
        panel.revalidate();
        panel.add(s);
        s.setVisible(true);
        panel.repaint();
        panel.revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panel.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        getContentPane().add(panel);
        panel.setBounds(20, 0, 910, 460);

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 470, 130, 31);

        jButton3.setText("Vender");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(90, 470, 120, 31);

        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(669, 470, 70, 31);

        setBounds(0, 0, 917, 594);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        to_sell s = new to_sell();
        s.setSize(900,500);
        s.setLocation(5, 5);
        panel.removeAll();
        panel.repaint();
        panel.revalidate();
        panel.add(s);
        s.setVisible(true);
        panel.repaint();
        panel.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        add s = new add();
        s.setSize(900,500);
        s.setLocation(80, 5);
        panel.removeAll();
        panel.repaint();
        panel.revalidate();
        panel.add(s);
        s.setVisible(true);
        panel.repaint();
        panel.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       principal p = new principal();
       p.setSize(950, 550);
       p.setTitle("Punto de venta");
       p.setLocationRelativeTo(null);
       p.setVisible(true);        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(hil==true){
            try{
                Thread.sleep(0);
            }catch (InterruptedException e){
                System.out.println("ERROR");
            }
            Login n = new Login ();
            n.setVisible(true);
            n.setLocationRelativeTo(null);
            this.setVisible(false);
            hil=false;
        }
    }
}
